services:
  testdb:
    image: postgres:14.2
    ports:
      - "5433:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=pick_a_username
      - POSTGRES_PASSWORD=pick_a_password
      - POSTGRES_DB=banco_de_testes

  localdb:
    image: postgres:14.2
    ports:
      - "5432:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=pick_a_username
      - POSTGRES_PASSWORD=pick_a_password
      - POSTGRES_DB=banco_local
