services:
  local:
    image: postgres:16.4
    ports:
      - "5432:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=taqtile
      - POSTGRES_PASSWORD=1234qwer
      - POSTGRES_DB=local

  testdb:
    image: postgres:16.4
    ports:
      - "5433:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=taqtile
      - POSTGRES_PASSWORD=1234qwer
      - POSTGRES_DB=testdb
